// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/montagao/monplan/models"
)

// AddPlanCreatedCode is the HTTP code returned for type AddPlanCreated
const AddPlanCreatedCode int = 201

/*AddPlanCreated Created

swagger:response addPlanCreated
*/
type AddPlanCreated struct {

	/*
	  In: Body
	*/
	Payload *models.Plan `json:"body,omitempty"`
}

// NewAddPlanCreated creates AddPlanCreated with default headers values
func NewAddPlanCreated() *AddPlanCreated {

	return &AddPlanCreated{}
}

// WithPayload adds the payload to the add plan created response
func (o *AddPlanCreated) WithPayload(payload *models.Plan) *AddPlanCreated {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the add plan created response
func (o *AddPlanCreated) SetPayload(payload *models.Plan) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *AddPlanCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(201)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*AddPlanDefault error

swagger:response addPlanDefault
*/
type AddPlanDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Plan `json:"body,omitempty"`
}

// NewAddPlanDefault creates AddPlanDefault with default headers values
func NewAddPlanDefault(code int) *AddPlanDefault {
	if code <= 0 {
		code = 500
	}

	return &AddPlanDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the add plan default response
func (o *AddPlanDefault) WithStatusCode(code int) *AddPlanDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the add plan default response
func (o *AddPlanDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the add plan default response
func (o *AddPlanDefault) WithPayload(payload *models.Plan) *AddPlanDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the add plan default response
func (o *AddPlanDefault) SetPayload(payload *models.Plan) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *AddPlanDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
