// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/montagao/monplan/models"
)

// DeleteEventNoContentCode is the HTTP code returned for type DeleteEventNoContent
const DeleteEventNoContentCode int = 204

/*DeleteEventNoContent Deleted

swagger:response deleteEventNoContent
*/
type DeleteEventNoContent struct {
}

// NewDeleteEventNoContent creates DeleteEventNoContent with default headers values
func NewDeleteEventNoContent() *DeleteEventNoContent {

	return &DeleteEventNoContent{}
}

// WriteResponse to the client
func (o *DeleteEventNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(204)
}

/*DeleteEventDefault error

swagger:response deleteEventDefault
*/
type DeleteEventDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewDeleteEventDefault creates DeleteEventDefault with default headers values
func NewDeleteEventDefault(code int) *DeleteEventDefault {
	if code <= 0 {
		code = 500
	}

	return &DeleteEventDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the delete event default response
func (o *DeleteEventDefault) WithStatusCode(code int) *DeleteEventDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the delete event default response
func (o *DeleteEventDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the delete event default response
func (o *DeleteEventDefault) WithPayload(payload *models.Error) *DeleteEventDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete event default response
func (o *DeleteEventDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteEventDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
