// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetPlanByIDHandlerFunc turns a function with the right signature into a get plan by Id handler
type GetPlanByIDHandlerFunc func(GetPlanByIDParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetPlanByIDHandlerFunc) Handle(params GetPlanByIDParams) middleware.Responder {
	return fn(params)
}

// GetPlanByIDHandler interface for that can handle valid get plan by Id params
type GetPlanByIDHandler interface {
	Handle(GetPlanByIDParams) middleware.Responder
}

// NewGetPlanByID creates a new http.Handler for the get plan by Id operation
func NewGetPlanByID(ctx *middleware.Context, handler GetPlanByIDHandler) *GetPlanByID {
	return &GetPlanByID{Context: ctx, Handler: handler}
}

/*GetPlanByID swagger:route GET /v1/plan/{id} getPlanById

GetPlanByID get plan by Id API

*/
type GetPlanByID struct {
	Context *middleware.Context
	Handler GetPlanByIDHandler
}

func (o *GetPlanByID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetPlanByIDParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
