// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/montagao/monplan/models"
)

// GetPlansOKCode is the HTTP code returned for type GetPlansOK
const GetPlansOKCode int = 200

/*GetPlansOK List the plans

swagger:response getPlansOK
*/
type GetPlansOK struct {

	/*
	  In: Body
	*/
	Payload []*models.Plan `json:"body,omitempty"`
}

// NewGetPlansOK creates GetPlansOK with default headers values
func NewGetPlansOK() *GetPlansOK {

	return &GetPlansOK{}
}

// WithPayload adds the payload to the get plans o k response
func (o *GetPlansOK) WithPayload(payload []*models.Plan) *GetPlansOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get plans o k response
func (o *GetPlansOK) SetPayload(payload []*models.Plan) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetPlansOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*models.Plan, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

/*GetPlansDefault generic error response

swagger:response getPlansDefault
*/
type GetPlansDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetPlansDefault creates GetPlansDefault with default headers values
func NewGetPlansDefault(code int) *GetPlansDefault {
	if code <= 0 {
		code = 500
	}

	return &GetPlansDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get plans default response
func (o *GetPlansDefault) WithStatusCode(code int) *GetPlansDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get plans default response
func (o *GetPlansDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the get plans default response
func (o *GetPlansDefault) WithPayload(payload *models.Error) *GetPlansDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get plans default response
func (o *GetPlansDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetPlansDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
