// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/montagao/monplan/models"
)

// GetPlanByIDOKCode is the HTTP code returned for type GetPlanByIDOK
const GetPlanByIDOKCode int = 200

/*GetPlanByIDOK OK

swagger:response getPlanByIdOK
*/
type GetPlanByIDOK struct {

	/*
	  In: Body
	*/
	Payload *models.Plan `json:"body,omitempty"`
}

// NewGetPlanByIDOK creates GetPlanByIDOK with default headers values
func NewGetPlanByIDOK() *GetPlanByIDOK {

	return &GetPlanByIDOK{}
}

// WithPayload adds the payload to the get plan by Id o k response
func (o *GetPlanByIDOK) WithPayload(payload *models.Plan) *GetPlanByIDOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get plan by Id o k response
func (o *GetPlanByIDOK) SetPayload(payload *models.Plan) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetPlanByIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*GetPlanByIDDefault error

swagger:response getPlanByIdDefault
*/
type GetPlanByIDDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Plan `json:"body,omitempty"`
}

// NewGetPlanByIDDefault creates GetPlanByIDDefault with default headers values
func NewGetPlanByIDDefault(code int) *GetPlanByIDDefault {
	if code <= 0 {
		code = 500
	}

	return &GetPlanByIDDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get plan by Id default response
func (o *GetPlanByIDDefault) WithStatusCode(code int) *GetPlanByIDDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get plan by Id default response
func (o *GetPlanByIDDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the get plan by Id default response
func (o *GetPlanByIDDefault) WithPayload(payload *models.Plan) *GetPlanByIDDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get plan by Id default response
func (o *GetPlanByIDDefault) SetPayload(payload *models.Plan) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetPlanByIDDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
