// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetPlansHandlerFunc turns a function with the right signature into a get plans handler
type GetPlansHandlerFunc func(GetPlansParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetPlansHandlerFunc) Handle(params GetPlansParams) middleware.Responder {
	return fn(params)
}

// GetPlansHandler interface for that can handle valid get plans params
type GetPlansHandler interface {
	Handle(GetPlansParams) middleware.Responder
}

// NewGetPlans creates a new http.Handler for the get plans operation
func NewGetPlans(ctx *middleware.Context, handler GetPlansHandler) *GetPlans {
	return &GetPlans{Context: ctx, Handler: handler}
}

/* GetPlans swagger:route GET /v1/plan/ getPlans

GetPlans get plans API

*/
type GetPlans struct {
	Context *middleware.Context
	Handler GetPlansHandler
}

func (o *GetPlans) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetPlansParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
