// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// UpdatePlanHandlerFunc turns a function with the right signature into a update plan handler
type UpdatePlanHandlerFunc func(UpdatePlanParams) middleware.Responder

// Handle executing the request and returning a response
func (fn UpdatePlanHandlerFunc) Handle(params UpdatePlanParams) middleware.Responder {
	return fn(params)
}

// UpdatePlanHandler interface for that can handle valid update plan params
type UpdatePlanHandler interface {
	Handle(UpdatePlanParams) middleware.Responder
}

// NewUpdatePlan creates a new http.Handler for the update plan operation
func NewUpdatePlan(ctx *middleware.Context, handler UpdatePlanHandler) *UpdatePlan {
	return &UpdatePlan{Context: ctx, Handler: handler}
}

/* UpdatePlan swagger:route PUT /v1/plan/{id} updatePlan

UpdatePlan update plan API

*/
type UpdatePlan struct {
	Context *middleware.Context
	Handler UpdatePlanHandler
}

func (o *UpdatePlan) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewUpdatePlanParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
