// Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi MM Plan API
For use with the Monta Monta Plan application


    Schemes:
      http
    Host: localhost
    BasePath: /
    Version: 1.0.0

    Consumes:
    - application/json

    Produces:
    - application/json

swagger:meta
*/
package restapi
